name: Update to Upstream

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "*/30 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: |
          git config --global user.name 'Gnoliyil'
          git config --global user.email 'gnoliyil@users.noreply.github.com'
          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)
          git remote add upstream https://fuchsia.googlesource.com/fuchsia/
          git fetch upstream
          
          git checkout master
          git rebase upstream/master && git push -f origin master
